language: python
python:
  - "3.6"

# command to install dependencies
#install:
  - pip install --progress-bar off requirements.txt

# command to run tests
#script:
#  - pytest

notifications:
  email:
    recipients:
      - schimpfabian@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
